package com.example.revolutlistener.notifications

import android.app.Notification
import android.os.Parcel
import android.os.Parcelable
import android.service.notification.StatusBarNotification
import android.text.TextUtils
import android.util.Log
import com.example.revolutlistener.database.Amount
import com.example.revolutlistener.database.Budget
import java.text.SimpleDateFormat
import java.util.*
import kotlin.collections.ArrayList
import kotlin.random.Random.Default.nextInt

private const val PAID = "Paid"

fun isMoneySpentNotification(noticationText: String): Boolean {

    // TODO analyse text generated by revolut and google pay to create regex expression
    return true;
}

fun parseMonetaryAmount(sbn: StatusBarNotification): Amount {

    // TODO analyse text generated by revolut and google pay to create regex expression
    // Placeholder for now

    return Amount(nextInt(0, 1000), nextInt(0, 100))
}
